// <auto-generated />
using System;
using ManageAccount.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ManageAccount.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312015131_CreateTableApp_Logs")]
    partial class CreateTableApp_Logs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageAccount.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.AccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("InterestTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("InterestTypeId");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppName")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("APP_NAME");

                    b.Property<string>("Exception")
                        .HasColumnType("CLOB")
                        .HasColumnName("EXCEPTION");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("LEVEL");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LOGGED_AT")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Logger")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("LOGGER");

                    b.Property<string>("MachineName")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("MACHINE_NAME");

                    b.Property<string>("Message")
                        .HasColumnType("CLOB")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Properties")
                        .HasColumnType("CLOB")
                        .HasColumnName("PROPERTIES");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("IX_APP_LOGS_LOGGED_AT");

                    b.HasIndex("Level", "LoggedAt")
                        .HasDatabaseName("IX_APP_LOGS_LEVEL_LOGGED_AT");

                    b.ToTable("APP_LOGS", (string)null);
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.InterestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 4)
                        .HasColumnType("DECIMAL(5,4)");

                    b.HasKey("Id");

                    b.ToTable("InterestTypes");
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.AccountBalance", b =>
                {
                    b.HasOne("ManageAccount.Data.Entities.Account", "Account")
                        .WithMany("AccountBalances")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageAccount.Data.Entities.InterestType", "InterestType")
                        .WithMany("AccountBalances")
                        .HasForeignKey("InterestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("InterestType");
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.Account", b =>
                {
                    b.Navigation("AccountBalances");
                });

            modelBuilder.Entity("ManageAccount.Data.Entities.InterestType", b =>
                {
                    b.Navigation("AccountBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
